import { GetStaticProps } from "next";
import { collection, getDocs } from "firebase/firestore";
import Image from "next/image";
import Head from "next/head";

import { db } from "../services/firebaseConnection";

import heroImg from "../../public/assets/hero.png";

import styles from "../styles/home.module.css";

interface HomeProps {
  posts: number;
  comments: number;
}

export default function Home({ comments, posts }: HomeProps) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tarefas+ | Organize suas tarefas de forma fácil</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.logoContent}>
          <Image
            className={styles.hero}
            alt="Logo Tarefas+"
            src={heroImg}
            priority
          />
        </div>
        <h1 className={styles.title}>
          Sistema feito para você organizar <br /> seus estudos e terefas
        </h1>

        <div className={styles.infoContent}>
          <section className={styles.box}>
            <span>+{posts} posts</span>
          </section>

          <section className={styles.box}>
            <span>+{comments} comentários</span>
          </section>
        </div>
      </main>
    </div>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const commentsRef = collection(db, "comments");
  const tasksRef = collection(db, "tasks");

  const commentsSnapshot = await getDocs(commentsRef);
  const postsSnapshot = await getDocs(tasksRef);

  return {
    props: {
      posts: postsSnapshot.size || 0,
      comments: commentsSnapshot.size || 0,
    },
    revalidate: 60, // revalidado a cada 60 segundos
  };
};
