name: Front-End Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read Node.js version from .nvmrc
        id: nvmrc
        run: echo "::set-output name=node_version::$(cat .nvmrc)"

      - name: Use Node.js version from .nvmrc
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvmrc.outputs.node_version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test:jest
